### ISSUE TITLE
Minimap

### ISSUE THREAD

**Issue by juliandoerner** [limetext/lime-qml#11]
Reopening old Issue in relevant Repo
https://github.com/limetext/lime/issues/204

**Comment by zoli** [comment]
There is an idea from https://github.com/limetext/lime/issues/301 that minimap should be just a transform of original View.

**Comment by ricochet1k** [comment]
Making the minimap a transform of the main view sounds like a great idea until you realize that the minimap shows a lot more lines than the main view does. QML won't render enough of the view for the minimap, and even if you force it to do so, the amount of graphics memory it would have to take up will be much higher.

Either way, the minimap is there and working. There are a few usability issues with it, and it currently doesn't scroll if the file is long, but it works.

**Comment by zoli** [comment]
In that case I'll close this issue.
