### ISSUE TITLE
 qml: menu not showing

### ISSUE THREAD

**Issue by gwenzek** [limetext/lime-qml#14]
> issue moved from limetext/support#5

Hey, I'm interested in contributing.
But I'm surprised by the look of the qml frontend versus the code.

For instance in [main.qml](https://github.com/limetext/lime-qml/blob/master/main/main.qml#L22) there is a menu bar.
But when I launch it, I don't have any menus (it's neither on the top of the screen like for other linux app).
![lime](https://cloud.githubusercontent.com/assets/5920036/10554108/c2de2b72-7460-11e5-864d-a25663750d51.png)

Is this normal ?

As a warmup task I wanted to try to replace the 'xx' and 'yy' in the status bar by the actual coordinates.
Do you think it's a good start, or it may reveal harder than it looks like ?

Answer from @zoli : 

>  About the menu its not normal the menu was showing before
> I'll look at that later and about the status bar i think you are starting at good point because you can get help from limetext/lime#487
> also there was an issue for qml to in limetext/lime#486 and the code for the termbox front end is here.

**Comment by zoli** [comment]
Checked this on my system the menu is showing maybe this is ubuntu related issue.

**Comment by gwenzek** [comment]
Apparently there is a bug in an [ubuntu package](https://bugs.launchpad.net/appmenu-qt5/+bug/1323853)

 robotology/yarp#521 suggest this workaround:

```
sudo apt-get remove --purge appmenu-qt5
```
