### ISSUE TITLE
Deleting line

### ISSUE THREAD

**Issue by zoli** [limetext/lime-qml#29]
on deleting a line the line below comes up but it will be duplicate I think this issue is related to rendering.

**Comment by ricochet1k** [comment]
I'm planning on making a binding for QAbstractItemModel so the list can be managed in Go code, instead of the weird go/qml bridge. It should be a lot faster too.

**Comment by ricochet1k** [comment]
Fixed via 85259cb963d471d61473e50dce29be1481fd2e53
