### ISSUE TITLE
Dependency has vanished

### ISSUE THREAD

**Issue by DanielHeath** [limetext/lime-qml#31]
gosubli.me/something-borrowed/gocode is not resolving, so I can't download/run the code for this repo.

Would this project be open to using one of the available vendoring schemes (e.g. `gb vendor`)?

**Comment by ricochet1k** [comment]
Um, I don't think that is a dependency of limetext. That's an autocompletion daemon, perhaps a dependency of the editor you are using?

**Comment by ricochet1k** [comment]
Perhaps to be more explicit, I don't have `gosubli.me/something-borrowed/gocode` downloaded in my $GOPATH or anywhere else for that matter, and I can build and run lime-qml just fine.

**Comment by ricochet1k** [comment]
Also, I think `github.com/nsf/gocode` is the same thing, so if you `go get github.com/nsf/gocode` that might resolve your issue.

**Comment by DanielHeath** [comment]
Ahh - I had an older clone which had lime-packages pre 9889d9c769f889a8b51209dbdd19c46f98d4c47e - which referred to `gosubli.me`. For some reason, `go get -u` was trying to update the dependency before downloading new code for lime-qml.

**Comment by DanielHeath** [comment]
I can reproduce this with a clean GOPATH for lime-html. Will open an issue there instead.
