### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by thewhitetulip** [limetext/lime-qml#41]
I followed the following guide: https://github.com/limetext/lime/wiki/Building

When I reached the end and tried to build the QML it gave me this error.

github.com/limetext/qml-go
In file included from ../../qml-go/all.cpp:2:
../../qml-go/cpp/capi.cpp:215:22: error: no type named 'setDesktopFileName' in 'QGuiApplication'
In file included from ../../qml-go/all.cpp:6:
In file included from ../../qml-go/cpp/goitemmodel_api.cpp:4:
In file included from ./cpp/util.cpp:2:
./cpp/util.h:13:9: warning: 'QStringFromGoString' has C-linkage specified, but returns user-defined type 'QString' which is incompatible with C [-Wreturn-type-c-linkage]

**Comment by zoli** [comment]
Related to https://github.com/limetext/qml-go/issues/4.

**Comment by ricochet1k** [comment]
setDesktopFileName has been removed for now. 0d03159d0ed45f668e00c79034d1a244fb3e2c0a
