### ISSUE TITLE
Executing main does not start anything

### ISSUE THREAD

**Issue by jparsert** [limetext/lime-qml#46]
So basically running ./main after i built it leads to the following error:
panic: runtime error: cgo result has Go pointer
....

**Comment by ricochet1k** [comment]
This is well known, we don't yet support Go 1.6 https://github.com/limetext/qml-go/issues/3

Make sure to join us on Gitter.im.

**Comment by jparsert** [comment]
so you only support things below 1.6 ?

**Comment by ricochet1k** [comment]
For now. We are working on support for it though.

Also, you can use GODEBUG=cgocheck=0 to run it with Go 1.6
